"""ADK Tool: Send translated mission briefing to volunteer.

CRITICAL PATH: This is the "wow moment" in the demo — a volunteer receives
a push notification in their own language, automatically translated by Gemini.
"""

import os


def send_alert(
    volunteer_id: str,
    mission_id: str,
    briefing: str,
    target_language: str = "en",
) -> dict:
    """Translate mission briefing to the volunteer's preferred language and send the alert.
    
    This is the most visually impressive moment in the demo: the volunteer receives
    a push notification with their mission briefing in their own language.
    
    Args:
        volunteer_id: The volunteer to notify
        mission_id: The mission this alert relates to
        briefing: The English mission briefing text (generated by you, the agent)
        target_language: ISO 639-1 language code for translation
            Supported: 'en' (English), 'fr' (French), 'ar' (Arabic),
            'es' (Spanish), 'tr' (Turkish), 'de' (German), 'pt' (Portuguese), 'zh' (Chinese)
    
    Returns delivery status including the translated briefing preview.
    """
    import google.generativeai as genai
    from firebase_admin import messaging
    from src.services.firebase import get_db

    db = get_db()

    LANGUAGE_NAMES = {
        "en": "English", "fr": "French", "ar": "Arabic", "es": "Spanish",
        "tr": "Turkish", "de": "German", "pt": "Portuguese", "zh": "Chinese",
    }

    # --- STEP 1: Translate the briefing via Gemini ---
    translated_briefing = briefing

    if target_language != "en" and os.getenv("GOOGLE_API_KEY"):
        try:
            genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))
            model = genai.GenerativeModel("gemini-2.0-flash")

            lang_name = LANGUAGE_NAMES.get(target_language, target_language)
            translation_prompt = (
                f"Translate this emergency mission briefing into {lang_name}. "
                f"This is for a disaster response volunteer. Keep it concise, urgent, and action-oriented. "
                f"Preserve all location names and coordinates. Only output the translated text:\n\n"
                f"{briefing}"
            )

            response = model.generate_content(translation_prompt)
            translated_briefing = response.text.strip()
        except Exception as e:
            translated_briefing = briefing
            # Log translation failure but don't block the alert
            db.collection("agent_logs").add({
                "timestamp": _now(),
                "action": "translation_failed",
                "error": str(e),
                "target_language": target_language,
                "mission_id": mission_id,
            })

    # --- STEP 2: Persist translated briefing to mission document ---
    db.collection("missions").document(mission_id).update({
        "translated_briefing": translated_briefing,
    })

    # --- STEP 3: Send push notification via FCM ---
    vol_doc = db.collection("volunteers").document(volunteer_id).get()
    if not vol_doc.exists:
        return {"error": f"Volunteer {volunteer_id} not found", "delivery": "failed"}

    volunteer = vol_doc.to_dict()
    delivery_result = {"channel": "none", "status": "no_contact_method"}

    if volunteer.get("fcm_token"):
        try:
            message = messaging.Message(
                notification=messaging.Notification(
                    title="🚨 Mission Assignment — CrisisRoute",
                    body=translated_briefing[:200],
                ),
                data={
                    "mission_id": mission_id,
                    "type": "mission_assignment",
                    "language": target_language,
                },
                token=volunteer["fcm_token"],
            )
            response = messaging.send(message)
            delivery_result = {"channel": "fcm", "status": "sent", "message_id": response}
        except Exception as e:
            delivery_result = {"channel": "fcm", "status": "failed", "error": str(e)}

    elif volunteer.get("phone"):
        try:
            from twilio.rest import Client

            twilio_client = Client(
                os.getenv("TWILIO_ACCOUNT_SID"),
                os.getenv("TWILIO_AUTH_TOKEN"),
            )
            sms = twilio_client.messages.create(
                body=f"CrisisRoute Mission: {translated_briefing[:300]}",
                from_=os.getenv("TWILIO_PHONE_NUMBER"),
                to=volunteer["phone"],
            )
            delivery_result = {"channel": "sms", "status": "sent", "message_sid": sms.sid}
        except Exception as e:
            delivery_result = {"channel": "sms", "status": "failed", "error": str(e)}

    # --- STEP 4: Log the alert ---
    db.collection("alert_logs").add({
        "volunteer_id": volunteer_id,
        "mission_id": mission_id,
        "volunteer_name": volunteer.get("display_name", "Unknown"),
        "channel": delivery_result["channel"],
        "status": delivery_result["status"],
        "target_language": target_language,
        "language_name": LANGUAGE_NAMES.get(target_language, target_language),
        "briefing_original": briefing[:200],
        "briefing_translated": translated_briefing[:200],
        "timestamp": _now(),
    })

    return {
        "volunteer_id": volunteer_id,
        "volunteer_name": volunteer.get("display_name", "Unknown"),
        "mission_id": mission_id,
        "language": target_language,
        "language_name": LANGUAGE_NAMES.get(target_language, target_language),
        "delivery": delivery_result,
        "briefing_translated_preview": translated_briefing[:150],
    }


def _now() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()
